version: '3.9'
services:  
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unlesss-stopped
    hostname: app
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - robyncrud

networks:
  robyncrud:
    driver: bridge